### ISSUE TITLE
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'cccbridge'!

### ISSUE THREAD

**Issue by opr** [tweaked-programs/cccbridge#45]
**Description**

Class not found error when loading on 1.19.2.

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'cccbridge'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoClassDefFoundError: com/simibubi/create/content/contraptions/wrench/IWrenchable
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 16 more
Caused by: java.lang.ClassNotFoundException: com.simibubi.create.content.contraptions.wrench.IWrenchable
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 30 more
```

**To Reproduce**
1. Create new 1.19.2 instance in MultiMC
2. Download and install:
-  [Create Fabric 1.19.2 v0.5.1.b Patch 1](https://modrinth.com/mod/create-fabric/version/0.5.1-b-build.1079+mc1.19.2)
- [CC: Restitched [1.19.1] 1.101.2](https://modrinth.com/mod/cc-restitched/version/1.101.2+1.19.1) and
- [CC: C Bridge v1.4.1 fabric](https://modrinth.com/mod/cccbridge/version/1.4.1-fabric)
3. Launch the instance

**Software (please complete the following information):**
 - Minecraft Version [e.g. 1.18.2] **1.19.2**
 - Mod Version [e.g. 1.2.1] **1.4.1**
 - ModLoader [Forge / Fabric] **Fabric**

**Comment by SammyForReal** [comment]
That is a known bug. This mod is not compatible with Create 1.5.1 yet, so you have to wait for the next release sorry.

**Comment by opr** [comment]
Ok thanks for letting me know!

**Comment by BraveCaperCat2** [comment]
1.5.1 isn't a version of create. the latest version is 0.5.1.

**Comment by SammyForReal** [comment]
Oh yeah thanks for reminding me about this issue.
Because I should mention here that **this got fixed within the latest release now.**

_(Also yeah I know its 0.5.1 and not 1.5.1, I have no idea why I went with this typo, everyone know what was meant tho so whatever ^^' )_
