### ISSUE TITLE
Crash on server side 1.18.2 1.5.0 Fabric

### ISSUE THREAD

**Issue by Erogig** [tweaked-programs/cccbridge#55]
**Description**
Latest version crashes when run on server

**To Reproduce**
1. Place Mod in mods folder of fabric server
2. run fabric server

**Expected behavior**
Server is supposed to launch like on client side

**Error**
[19:37:50] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'cccbridge'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.21.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:0.11.2]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_5617
        at cc.tweaked_programs.cccbridge.CCCBridge.onInitialize(CCCBridge.java:35) ~[cccbridge-mc1.18.2-fabric-v1.5.0.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
        ... 8 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_5617
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at cc.tweaked_programs.cccbridge.CCCBridge.onInitialize(CCCBridge.java:35) ~[cccbridge-mc1.18.2-fabric-v1.5.0.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
        ... 8 more

**Software (please complete the following information):**
 - Minecraft Version [1.18.2]
 - Mod Version [1.5.0]
 - ModLoader [Fabric]

Based on my limited understanding it seems to be caused by the new Animatronics

**Comment by SammyForReal** [comment]
Thank you for reporting this!
This seems to be an error on both 1.18.2 and 1.19.2 on Fabric due to how we register entities.
~~(We mixed together client-side and server-side methods in one, a dumb mistake)~~

I will quickly fix this.

**Comment by SammyForReal** [comment]
Solved with v.1.5.1
