### ISSUE TITLE
[1.19.2 Bug] CC:Bridge causing huge recipes packet breaking rei

### ISSUE THREAD

**Issue by itsdinkd** [tweaked-programs/cccbridge#65]
**Description**
Adding CC:Bridge into AQM2 for 1.19.2 causes a huge packet for recipe sync, breaking rei. Basically, REI no longer works. 

This is whats shown in console
```
java.lang.IllegalArgumentException: Packet too big (is 8434739, should be less than 8388608): net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket@782dd841
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:48) [server-intermediary.jar:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) [server-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

Oddly, when i left CC:Bridge on client side, and not in server, REI showed, and i was able to join the server. 

**To Reproduce**
1. Add cccbridge-mc1.19.2-fabric-v1.5.1.jar to Server and Client in AQM2 Modpack
2. Join a locally hosted server, or dedicated server.
3. REI Breaks.

**Expected behavior**
REI to work

**Software (please complete the following information):**
 - Minecraft Version [e.g. 1.18.2]: 1.19.2
 - Mod Version [e.g. 1.2.1]. cccbridge-mc1.19.2-fabric-v1.5.1.jar
 - ModLoader [Forge / Fabric] fabric

**Comment by itsdinkd** [comment]
Well now im getting the issue again even with CC:Bridged removed. I think there is another source of mod confliction here interacting with CC:Bridge added and something else. stay tuned will update.

**Comment by SammyForReal** [comment]
Cccbridge does nothing within the REI API nor custom recipes.

I also can't see where cccbridge is involved in the given logs.

I will close this issue as I don't think that this mod causes this crash. Feel free to reopen this however, if you figured the opposite.

**Comment by itsdinkd** [comment]
I get what you're saying and it makes no sense (the issue being solved once I removed it). 

I ended up figuring out when Cc bridge, brewin and chewin,and create slice and dice are not in the pack, REI works everytime. I do not get a packet too big error. But when they are in, i do get the error.

Not sure how to chalk this up.

**Comment by SammyForReal** [comment]
can you show more of the logs?
Also, when does this happen? On server side? Or also on single player worlds? Or on startup on client/server?

**Comment by itsdinkd** [comment]
It happened magically again after I released the update of my pack, even though I verified 6 different times it was working again before doing so. 

The pack update does not include cc bridge so you're right there's no way it's Cc bridge/apart of the conflictions
